#!/bin/bash
# aerth slackbuild script v99.99.9998
if [[ $1 == "clean" ]]; then
rm -Rf ./suprtmp
exit 0;
fi
if [[ $1 == "update" ]]; then
curl -o $(which suprslack) \
   https://raw.githubusercontent.com/aerth/sh/master/sbin/suprslack
exit 0;
fi
echo "Paste Source URL (http://example.com/source.tar.bz2)"
read SOURCEURL
echo "Paste SlackBuild URL (http://slackbuilds.org/etc/etc/pkg.tar.gz)"
read SLACKBUILD
echo Entering ./suprtmp ...
mkdir suprtmp && cd suprtmp
echo Downloading $SLACKBUILD with curl ...
f="${SLACKBUILD##*/}"
curl -o "${f}" $SLACKBUILD
echo Extracting $f
tar xf "${f}"
ftar="${f%.*}"
pkgname="${ftar%.*}"
cd $pkgname
echo "We are installing $pkgname, if not... press CTRL+C now!"
sleep 3
echo Downloading $SOURCEURL
srcf="${SOURCEURL##*/}"
curl -o "${srcf}" $SOURCEURL
cat README
echo "Enter build args ( ARG1=value ARG2=etc ARG3=yes )"
read $ARGGGG
export $ARGGGG
echo "We are about to run this command using \`sudo su -l\`"
echo sh $ARGGGG $pkgname.SlackBuild
#echo sh $ARGGGG ${f%.*}.SlackBuild"
echo
echo Building...
realpwd=${pwd}
$ARGGGG ./$pkgname.SlackBuild
echo Installing in...
sleep 1
echo 3
sleep 1
echo 2
sleep 1
echo 1
sleep 1
installpkg /tmp/$pkgname-*.tgz
echo All done!
exit 0
