#!/bin/bash
# aerth slackbuild script v99.99.9998

# For "upgrade" check out the available packages at:
# http://www.slackware.com/security/list.php?l=slackware-security&y=2016
# or https://rss.packetstormsecurity.com/files/os/slackware/

set -e
if [[ $1 == "help" ]]; then
echo "$0 update | install | upgrade | clean"
exit 0;
fi
if [[ $1 == "clean" ]]; then
rm -Rf ./suprtmp
exit 0;
fi
if [[ $1 == "update" ]]; then
curl -o $(which suprslack) \
   https://raw.githubusercontent.com/aerth/sh/master/sbin/suprslack
exit 0;
fi
if [[ $1 == "upgrade" ]]; then

if [[ -z $2 ]]; then
echo Example: $0 $1 n/php

exit 1
fi
echo "Upgrading $2"
mkdir /tmp/supr-upgrade || true
cd /tmp/supr-upgrade
wget ftp://ftp.slackware.com/pub/slackware/slackware64-current/slackware64/$2*
f="${2##*/}"
upgradepkg /tmp/supr-upgrade/$f*.txz
exit 0;
fi
echo "Paste Source URL (http://example.com/source.tar.bz2)"
read SOURCEURL
echo "Paste SlackBuild URL (http://slackbuilds.org/etc/etc/pkg.tar.gz)"
read SLACKBUILD
echo Entering ./suprtmp ...
mkdir suprtmp && cd suprtmp
echo Downloading $SLACKBUILD with curl ...
f="${SLACKBUILD##*/}"
curl -o "${f}" $SLACKBUILD
echo Extracting $f
tar xf "${f}"
ftar="${f%.*}"
pkgname="${ftar%.*}"
cd $pkgname
echo "We are installing $pkgname, if not... press CTRL+C now!"
sleep 3
echo Downloading $SOURCEURL
srcf="${SOURCEURL##*/}"
curl -o "${srcf}" $SOURCEURL
cat README
echo "Great time to edit $(pwd)/$pkgname.SlackBuild !"
echo "Enter build args ( ARG1=value ARG2=etc ARG3=yes )"
read $ARGGGG
export $ARGGGG
echo $ARGGGG $pkgname.SlackBuild
#echo sh $ARGGGG ${f%.*}.SlackBuild"
echo
echo Building...
realpwd=${pwd}
$ARGGGG ./$pkgname.SlackBuild
echo Installing in...
sleep 1
echo 3
sleep 1
echo 2
sleep 1
echo 1
sleep 1
installpkg /tmp/$pkgname-*.tgz
echo All done!
exit 0
